### ISSUE TITLE
The power menu in the QS Panel overlaps other buttons when expanded

### ISSUE THREAD

**Issue by sbeve72** [Rayzeq/quick-settings-audio-panel#24]
[Screencast from 2023-10-01 12-00-54.webm](https://github.com/Rayzeq/quick-settings-audio-panel/assets/65838896/dd5a9e26-6887-4c98-b6ec-067e3aa8217f)

**Comment by Rayzeq** [comment]
Your issue has made me notice that the power menu is indeed too high (although not high enough to overlap anything on my computer).
I think I've fixed the issue, but I'm not 100% sure. Could you please install [this version](https://github.com/Rayzeq/quick-settings-audio-panel/files/12777103/quick-settings-audio-panel%40rayzeq.github.io.shell-extension.zip) (instructions are in the readme) and confirm that the issue is fixed?

**Comment by sbeve72** [comment]
How it looks:
![Screenshot from 2023-10-01 18-58-19](https://github.com/Rayzeq/quick-settings-audio-panel/assets/65838896/f93baa7d-8b67-4481-a70e-e362ba21bb49)

How it should look:
![Screenshot from 2023-10-01 18-58-05](https://github.com/Rayzeq/quick-settings-audio-panel/assets/65838896/4b35b81f-c4e8-4bf9-a8c0-c022df7d6033)

**Comment by sbeve72** [comment]
Also the power menu remains open on dismissing the QS Panel by clicking elsewhere. So, when I open the QS Panel again, the power menu opens as well. And if I dismiss it, and try to press other keys like the Meta key to open overview, it doesn't work.

**Comment by Rayzeq** [comment]
I have no idea what the issue is this time, and given that it works with the default theme, it's probably due to your theme (I've also noticed that my extension makes the font change). I can't think of a workaround, and I guess that's good enough, so I consider this issue fixed.
Regarding the second issue you mentioned, the only way I've found to close the QS panel without closing the submenus first is to take a screenshot, but this does cause the same issue. I think I know how to fix it, so it should be quick.

**Comment by Rayzeq** [comment]
The second issue is now fixed in version 24

**Comment by sbeve72** [comment]
Thanks a lot. Btw, the first issue is still present with the default theme. Just to let u know but you're free to keep this issue closed if u don't want to fix it.

**Comment by Rayzeq** [comment]
It's really strange, for me the issue is completely fixed with the default theme, and only slightly visible with your theme.
But anyway, if I can't reproduce it, I have no way of knowing the source of the issue, so I guess it'll stay that way.
