### ISSUE TITLE
Crashes after resuming from suspension, removing the first row of quick settings

### ISSUE THREAD

**Issue by nawordar** [Rayzeq/quick-settings-audio-panel#36]
After my PC resumes, sometimes the extension crashes removing the top row of quick settings:

![Quick setting panel without top row](https://github.com/Rayzeq/quick-settings-audio-panel/assets/26769700/77371d29-f590-4cc0-872b-8da486c09abc)

If after resuming the extension does not crash, I can still reproduce the error by turning off the extension in Extension Manager:

![Extension Manager screenshot displaying an error message](https://github.com/Rayzeq/quick-settings-audio-panel/assets/26769700/bb71a03c-56fd-4d83-8bc4-f2122d788d43)

Error log:

```
Feb 01 17:26:49 cdro-pc gnome-shell[55237]: Extension quick-settings-audio-panel@rayzeq.github.io: TypeError: item.menu.actor.get_parent() is null
                                            
                                            Stack trace:
                                              removeItem@file:///home/cdro/.local/share/gnome-shell/extensions/quick-settings-audio-panel@rayzeq.github.io/libs/libpanel/main.js:638:20
                                              _move_quick_settings@file:///home/cdro/.local/share/gnome-shell/extensions/quick-settings-audio-panel@rayzeq.github.io/libs/libpanel/main.js:933:13
                                              _disable@file:///home/cdro/.local/share/gnome-shell/extensions/quick-settings-audio-panel@rayzeq.github.io/libs/libpanel/main.js:899:8
                                              disable@file:///home/cdro/.local/share/gnome-shell/extensions/quick-settings-audio-panel@rayzeq.github.io/libs/libpanel/main.js:771:13
                                              _cleanup_panel@file:///home/cdro/.local/share/gnome-shell/extensions/quick-settings-audio-panel@rayzeq.github.io/extension.js:167:18
                                              disable@file:///home/cdro/.local/share/gnome-shell/extensions/quick-settings-audio-panel@rayzeq.github.io/extension.js:65:14
                                              _callExtensionDisable@resource:///org/gnome/shell/ui/extensionSystem.js:202:32
                                              _onEnabledExtensionsChanged@resource:///org/gnome/shell/ui/extensionSystem.js:619:24
                                              _loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:705:18
                                              createCheckedMethod/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:730:46
                                              disableExtension@resource:///org/gnome/shell/ui/extensionSystem.js:292:29
                                              DisableExtension@resource:///org/gnome/shell/ui/shellDBus.js:457:38
                                              _handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:329:38
                                              _wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:408:34
                                              @resource:///org/gnome/shell/ui/init.js:21:20
```

**Comment by Rayzeq** [comment]
This is probably fixed by version 37, please reopen the issue if it isn't.

**Comment by nawordar** [comment]
Unfortunately, still happens on version 41. Stack trace looks almost the same:

```
Feb 09 23:32:34 cdro-pc gnome-shell[44588]: Extension quick-settings-audio-panel@rayzeq.github.io: TypeError: item.menu.actor.get_parent() is null
                                            
                                            Stack trace:
                                              removeItem@file:///home/cdro/.local/share/gnome-shell/extensions/quick-settings-audio-panel@rayzeq.github.io/libs/libpanel/main.js:638:20
                                              _move_quick_settings@file:///home/cdro/.local/share/gnome-shell/extensions/quick-settings-audio-panel@rayzeq.github.io/libs/libpanel/main.js:933:13
                                              _disable@file:///home/cdro/.local/share/gnome-shell/extensions/quick-settings-audio-panel@rayzeq.github.io/libs/libpanel/main.js:899:8
                                              disable@file:///home/cdro/.local/share/gnome-shell/extensions/quick-settings-audio-panel@rayzeq.github.io/libs/libpanel/main.js:771:13
                                              _cleanup_panel@file:///home/cdro/.local/share/gnome-shell/extensions/quick-settings-audio-panel@rayzeq.github.io/extension.js:172:18
                                              disable@file:///home/cdro/.local/share/gnome-shell/extensions/quick-settings-audio-panel@rayzeq.github.io/extension.js:65:14
                                              _callExtensionDisable@resource:///org/gnome/shell/ui/extensionSystem.js:202:32
                                              _onEnabledExtensionsChanged@resource:///org/gnome/shell/ui/extensionSystem.js:619:24
                                              async*_sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:799:20
                                              ExtensionManager/<@resource:///org/gnome/shell/ui/extensionSystem.js:44:18
                                              _callHandlers@resource:///org/gnome/gjs/modules/core/_signals.js:130:42
                                              _emit@resource:///org/gnome/gjs/modules/core/_signals.js:119:10
                                              _sync@resource:///org/gnome/shell/ui/sessionMode.js:212:14
                                              pushMode@resource:///org/gnome/shell/ui/sessionMode.js:170:14
                                              activate@resource:///org/gnome/shell/ui/screenShield.js:617:34
                                              lock@resource:///org/gnome/shell/ui/screenShield.js:684:14
                                              _prepareForSleep@resource:///org/gnome/shell/ui/screenShield.js:250:22
                                              _callHandlers@resource:///org/gnome/gjs/modules/core/_signals.js:130:42
                                              _emit@resource:///org/gnome/gjs/modules/core/_signals.js:119:10
                                              _prepareForSleep@resource:///org/gnome/shell/misc/loginManager.js:207:14
                                              _callHandlers@resource:///org/gnome/gjs/modules/core/_signals.js:130:42
                                              _emit@resource:///org/gnome/gjs/modules/core/_signals.js:119:10
                                              _convertToNativeSignal@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:152:19
                                              @resource:///org/gnome/shell/ui/init.js:21:20
```

**Comment by Rayzeq** [comment]
Since version 37 hasn't solved the problem, I think it's probably incompatibility with another extension.
Could you try to reproduce the issue with only QSAP enabled, and if that solves it, try to isolate the extension that's causing the issue ?

Until the issue is fixed, you can use this version, which contains a workaround that should prevent the extension from crashing: [quick-settings-audio-panel@rayzeq.github.io.shell-extension.zip](https://github.com/Rayzeq/quick-settings-audio-panel/files/14228986/quick-settings-audio-panel%40rayzeq.github.io.shell-extension.zip)

**Comment by nawordar** [comment]
It seems that the conflicting extension is [Brightness control using ddcutil](https://github.com/daitj/gnome-display-brightness-ddcutil). I found that the fastest way to reproduce the problem is to enable BCUD and re-enabling QSAP a few times, until it crashes. Looks like some sort of race condition

**Comment by Rayzeq** [comment]
The issue is caused by BCUD manually adding items to the quick settings instead of using the method provided by gnome. I have published the workaround that prevents QSAP from crashing as a new version (v43).
